"""Persistence-neutral repository interfaces and temporary implementations."""

from .interfaces import (
    ActionProposalRepository,
    ApprovalRepository,
    DecisionRepository,
    DuplicateRecordError,
    EventRepository,
    ImmutableRecordError,
    RecordNotFoundError,
    RepositoryError,
    ResultRepository,
    TaskRepository,
    WorkspaceRepository,
)
from .memory import (
    InMemoryRepositories,
    MemoryApprovalRepository,
    MemoryActionProposalRepository,
    MemoryDecisionRepository,
    MemoryEventRepository,
    MemoryResultRepository,
    MemoryTaskRepository,
    MemoryWorkspaceRepository,
)
from .sqlite import (
    CURRENT_SCHEMA_VERSION,
    DEFAULT_DATABASE_PATH,
    SQLiteApprovalRepository,
    SQLiteActionProposalRepository,
    SQLiteDatabase,
    SQLiteDecisionRepository,
    SQLiteEventRepository,
    SQLiteRepositories,
    SQLiteResultRepository,
    SQLiteTaskRepository,
    SQLiteWorkspaceRepository,
)

__all__ = [
    "ActionProposalRepository",
    "ApprovalRepository",
    "CURRENT_SCHEMA_VERSION",
    "DEFAULT_DATABASE_PATH",
    "DecisionRepository",
    "DuplicateRecordError",
    "EventRepository",
    "ImmutableRecordError",
    "InMemoryRepositories",
    "MemoryApprovalRepository",
    "MemoryActionProposalRepository",
    "MemoryDecisionRepository",
    "MemoryEventRepository",
    "MemoryResultRepository",
    "MemoryTaskRepository",
    "MemoryWorkspaceRepository",
    "RecordNotFoundError",
    "RepositoryError",
    "ResultRepository",
    "SQLiteApprovalRepository",
    "SQLiteActionProposalRepository",
    "SQLiteDatabase",
    "SQLiteDecisionRepository",
    "SQLiteEventRepository",
    "SQLiteRepositories",
    "SQLiteResultRepository",
    "SQLiteTaskRepository",
    "SQLiteWorkspaceRepository",
    "TaskRepository",
    "WorkspaceRepository",
]
