"""Core contracts and invariants shared by every KAIOS agent."""

from .contracts import (
    DEFAULT_WORKSPACE_ID,
    ActionProposal,
    AgentResult,
    AgentTask,
    ApprovalRequest,
    ApprovalStatus,
    DecisionRecord,
    ResultStatus,
    RiskClassification,
    TaskEvent,
    TaskStatus,
    Workspace,
    WorkspaceStatus,
    create_default_workspace,
)
from .lifecycle import (
    ALLOWED_TASK_TRANSITIONS,
    InvalidTaskTransition,
    can_transition,
    transition_task,
    validate_transition,
)
from .workspaces import (
    RelationshipValidationError,
    WorkspaceBoundaryError,
    records_for_workspace,
    require_same_workspace,
    validate_approval_for_proposal,
    validate_decision_context,
    validate_event_for_task,
    validate_proposal_for_task,
    validate_result_for_task,
    validate_task_relationship,
)

__all__ = [
    "ALLOWED_TASK_TRANSITIONS",
    "DEFAULT_WORKSPACE_ID",
    "ActionProposal",
    "AgentResult",
    "AgentTask",
    "ApprovalRequest",
    "ApprovalStatus",
    "DecisionRecord",
    "InvalidTaskTransition",
    "RelationshipValidationError",
    "ResultStatus",
    "RiskClassification",
    "TaskEvent",
    "TaskStatus",
    "Workspace",
    "WorkspaceBoundaryError",
    "WorkspaceStatus",
    "can_transition",
    "create_default_workspace",
    "records_for_workspace",
    "require_same_workspace",
    "transition_task",
    "validate_approval_for_proposal",
    "validate_decision_context",
    "validate_event_for_task",
    "validate_proposal_for_task",
    "validate_result_for_task",
    "validate_task_relationship",
    "validate_transition",
]
